### PR TITLE
Added language detection for non-english youtube videos

### LINKED ISSUE #385: feature request: youtube video in other language
### 🚀 The feature

Being able to use the "youtube_video" format in other language like for example 'French'. 
Today is not working when you put the link of a french youtube video.
Maybe there is a way to define the target language for youtube audio transcription (using Langchain behind) but I've not found any mention about this in the documentation. 

### Motivation, pitch

Be able to use the 'youtube_video' option with youtube video links not in English (by default) 

### Alternatives

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by anantoj**
## Description

Invoking `app.add()` on non-english youtube videos would cause a `NoTranscriptFound` error. There is already a [pull request](https://github.com/embedchain/embedchain/pull/774) that fixes the issue by specify an additional argument in the config file, but it has not been merged until today. Ideally `app.add()` also automatically detects the language in the youtube transcript, instead having to manually specify the language in the beginning.

Fixes #385 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

I simply invoked `app.add()` on various non-english youtube videos, and the `NoTranscriptFound` error no longer appears.

Please delete options that are not relevant.

- [x] Unit Test

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

## Maintainer Checklist

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] Made sure Checks passed

### CODE REVIEW

**Comment by anantoj** [comment]
@LeonieFreisinger Thanks for pointing out the issue. I was not aware that the test suite uses a dummy `VIDEO_ID`, which breaks the `video_id`  extraction. There's also another issue caused a recent commit [78301ee](https://github.com/embedchain/embedchain/commit/78301ee63d4927016764407bbeeb8a0ee28c1cb7) that modifies the metadata. I fixed all the issues in my recent commit and `test_youtube_video/test_load_data` passed on my end. Let me know if it's all good for you

**Comment by LeonieFreisinger** [comment]
@anantoj thanks for your fast answer!
I tested your code with this url: `https://www.youtube.com/watch?v=RG7Edrbhdpk`. I get an error "Could not retrieve a transcript for the video". Can you have a look into it?
Besides that, your code works fine for me. Thanks!

**Comment by anantoj** [comment]
@LeonieFreisinger it seems that your video just doesn't have a transcript, which causes the issue. 


It's also a warning raised by `youtube_transcript_api` instead of an error. The error, at least on my end, is a `ValueError` on embedchain's Youtube video loader [here](https://github.com/embedchain/embedchain/blob/ebc5e25f9825f1f3acef45593a1457550b089fd1/embedchain/loaders/youtube_video.py#L29) which is raised when the transcript is not found.

**Comment by LeonieFreisinger** [comment]
@anantoj You are right! So it should be fine. 
@deshraj @taranjeet The changes in the PR look good to me. Can you please re-trigger the workflows and merge the PR?

**Comment by Dev-Khant** [comment]
@anantoj Can you please resolve the merge conflicts so that we can merge the PR?

**Comment by anantoj** [comment]
Hi @Dev-Khant, I've resolved the conflicts

**Review by deshraj — APPROVED** [review]

**Comment by deshraj** [comment]
@anantoj can you please fix the lint issues in the PR? You can run `make lint format` to format the code. Once that is fixed, we are ready to merge the PR.

**Comment by anantoj** [comment]
Hi @deshraj, I fixed the lint issues.

**Pull request merged**
