### PR TITLE
LanceDB Integration

### PR DESCRIPTION
**Pull request by PrashantDixit0**
## Description

This PR adds LanceDB vector database.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

I have written tests for the LanceDB vector database in `tests/vectordb/test_lancedb.py`
- [x] Test Script (please provide)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

## Maintainer Checklist

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] Made sure Checks passed

### CODE REVIEW

**Comment by AyushExel** [comment]
hey guys can we let this reviewed? Thanks!

**Comment by LeonieFreisinger** [comment]
@PrashantDixit0  thanks for proposing these changes. I had a look at your code. There are 2 minor problems with the imports. 
`embedchain/config/vectordb/lancedb.py`: 
please correct the import line to
`from embedchain.helpers.json_serializable import register_deserializable`

tests/vectordb/test_lancedb.py:
please correct import line to:
```
from embedchain.config import AppConfig
from embedchain.config.vectordb.lancedb import LanceDBConfig
```

Further, lancedb is not yet added to the `factory.py` and the `misc.py`. Can you add this?

**Comment by PrashantDixit0** [comment]
@LeonieFreisinger  Thank you for highlighting it, I'll add it

**Comment by LeonieFreisinger** [comment]
@PrashantDixit0  What example did you use to test your code? Can you provide me with a quick example and a sample config? Thanks. 
Could you also add an example to the docs?

**Comment by PrashantDixit0** [comment]
Sure @LeonieFreisinger, I'll add an example notebook in `notebooks` folder

**Comment by PrashantDixit0** [comment]
@LeonieFreisinger, I have added an example notebook and tested the whole flow. Is it good to merge?

**Comment by PrashantDixit0** [comment]
@deshraj Can you start reviewing it?

**Comment by Dev-Khant** [comment]
Hi @PrashantDixit0 Can you please resolve the conflicts?

**Comment by PrashantDixit0** [comment]
Sure

**Pull request closed without merging**
