### PR TITLE
add add_file function to load text from file

### PR DESCRIPTION
**Pull request by gasolin**
add a handy function to load local text file (for example if you own several contents locally) instead of 2 step: load file then use `add_local` to pass as local strings

### CODE REVIEW

**Comment by 1MikeMakuch** [comment]
It's there as a loader, "text"

https://github.com/embedchain/embedchain/blob/main/embedchain/embedchain.py#L49

**Comment by gasolin** [comment]
@1MikeMakuch its a different thing

the `add_file` accept file path instead of pass string directly,
after file loaded/content ready,
it allow to pass `text` to use textLoader load content (can refer the readme in the PR)

**Comment by 1MikeMakuch** [comment]
@gasolin I'm afraid I don't quite follow exactly everything you're saying. But this works for me:

```chat_bot.add_local("text", "./myTextFile.txt")```

**Comment by 1MikeMakuch** [comment]
@gasolin Ah yes, thank you. I'm using this PR now. Thanks.

**Comment by cachho** [comment]
Hey, the idea is good, but the implementation is in a different style. Please don't make it a method of the main class. Please add a loader and chunker, the loader can internally use the text loader.

**Review by cachho — CHANGES_REQUESTED** [review]
Hey, the idea is good, but the implementation is in a different style. Please don't make it a method of the main class. Please add a loader and chunker, the loader can internally use the text loader.

**Comment by cachho** [comment]
> @cachho : should this be a separate data type? like `txt` file?

this abstracts two lines of code. Two lines of code that would allow important customization like adding line by line or the whole text at once. So it's up to you how much abstraction you want to add, I don't think we need it.

But you are right, if we add it it has to be it's own datatype. Maybe you could even do `txt_file_lines` and `txt_file` to deal with the customization I mentioned.

**Comment by cachho** [comment]
opened #417 to implement this the right way. closing this.

**Pull request closed without merging**
