### PR TITLE
Used app.db.reset() instead of app.reset()

### PR DESCRIPTION
**Pull request by subhajit20**
## Description
Use app.db.reset() instead of app.reset() 
Issue - #711 

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (does not change functionality, e.g. code style improvements, linting)
- [ ] Documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

Please delete options that are not relevant.

- [ ] Unit Test
- [ ] Test Script (please provide)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

## Maintainer Checklist

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] Made sure Checks passed

### CODE REVIEW

**Comment by subhajit20** [comment]
hey @taranjeet  please check this and let me know for further correction.

**Comment by taranjeet** [comment]
Hey @subhajit20 : we should not update the test. We should fix the warning from the source. Basically we need to update the code where reset function is defined.

**Comment by subhajit20** [comment]
> Hey @subhajit20 : we should not update the test. We should fix the warning from the source. Basically we need to update the code where reset function is defined.

Okay let me check.

**Comment by subhajit20** [comment]
> Hey @subhajit20 : we should not update the test. We should fix the warning from the source. Basically we need to update the code where reset function is defined.

hey should I remove this `logging.warning("DEPRECATION WARNING: Please use `app.db.reset()` instead of `App.reset()`.")` from the reset funtion ?

**Comment by subhajit20** [comment]
Hey @taranjeet , can you help out?

**Comment by taranjeet** [comment]
Hey @subhajit20 , sure.
so you will have to remove the function `reset()` located in `embedchain/embedchain.py`.
You will have to make sure that everything works after removing this function - all tests, code should work.

**Comment by subhajit20** [comment]
@taranjeet  hey, should I remove the entire reset function or anything else?

**Comment by subhajit20** [comment]
Hey @taranjeet,  I have removed the reset function.

**Comment by subhajit20** [comment]
hey @taranjeet can you help out?

**Comment by deshraj** [comment]
Hey @subhajit20 thanks for the reminder. We don't need to solve this issue since this has already been taken care of in a refactor and we believe that we don't need it anymore.

**Pull request closed without merging**
