### PR TITLE
Feat: Improve test coverage of DocsSiteLoader

### LINKED ISSUE #697: Improve test coverage of embedchain/loaders/docs_site_loader.py
### 🚀 The feature

As per this coverage report, https://drive.google.com/file/d/1L8HMFafqvlysc6GWXG8sy4ErVuBusbZP/view
the current code coverage is low.
We need to improve it.

### Motivation, pitch

Better code coverage makes development faster and helps in minimizing the errors.

### PR DESCRIPTION
**Pull request by SerSamgy**
## Description

Adds 100% test coverage for DocsSiteLoader

Fixes #697 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (does not change functionality, e.g. code style improvements, linting)
- [ ] Documentation update

## How Has This Been Tested?

- [x] Unit Test
- [ ] Test Script (please provide)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

## Maintainer Checklist

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] Made sure Checks passed

### CODE REVIEW

**Comment by deshraj** [comment]
@SerSamgy can you please rebase your branch with main branch? Seems like the tests are failing since the branch is stale.

**Comment by SerSamgy** [comment]
Hi @deshraj 👋🏻 I've rebased the main branch.

**Review by deshraj — APPROVED** [review]

**Comment by deshraj** [comment]
Ah, looks like you will have to rebase again due to recent changes in the main branch 😅

**Comment by SerSamgy** [comment]
@deshraj You could merge it 🙂

**Pull request merged**
