### PR TITLE
fix: initialize embedding function manually

### PR DESCRIPTION
**Pull request by cachho**
Resolves: #190

### CODE REVIEW

**Comment by cachho** [comment]
actually, I had to move the default database out of the config too, because Chroma depends on the embedding function to be initialized.

**Comment by taranjeet** [comment]
@cachho : the PR looks good.
there is a merge conflict, can you please resolve that?

**Comment by cachho** [comment]
> @cachho : the PR looks good. there is a merge conflict, can you please resolve that?

resolved

**Comment by taranjeet** [comment]
looks good after the merge conflict is resolved

**Review by taranjeet — APPROVED** [review]

**Comment by cachho** [comment]
Merge conflicts resolved, they were quite a mess please review again.

**Pull request merged**
