### PR TITLE
# Project Tools

### PR DESCRIPTION
**Pull request by amjadraza**
Addressing #72 and #40 

1. `poetry` added as a package and Venv manager
2. Set up Auto Tests
3. Added Examples Placeholder
4. Added `CONTRIBUTING.md` guide
5. Added `CI/CD` pipeline with GitHub
6. Added `black` for code formatting
7. Added `ruff` for Linting
8. Added `autotests` using `pytest`

TODO: PyTests are blocked in `pre-commit run` yet. But can easily be activated.

### CODE REVIEW

**Comment by amjadraza** [comment]
@taranjeet looking for your feedback. If we want to adapt these changes, I can further work on it. 

**docs** feature can easily added with few hours of work.

**Comment by cachho** [comment]
Just curious, why poetry?

**Comment by amjadraza** [comment]
POETRY is an emerging Project and Environment manager and is being adopted by python developers. 

Read the below article on comparisons. 

https://medium.com/towards-data-science/poetry-a-better-way-to-manage-python-dependencies-bd7b5f1eab25

**Comment by taranjeet** [comment]
@cachho : can you start taking up this PR and collaborate with @amjadraza to get this merged.
we should definitely split the PR and right now lets start with adding contributing guidelines, and then a proper linting setup.
we can focus on next items post this.

**Comment by amjadraza** [comment]
I suggest migrating to the POETRY environment and package manager as a first step.

**Comment by taranjeet** [comment]
@amjadraza : @deshraj has raised a PR: https://github.com/embedchain/embedchain/pull/208
Both of you are trying to solve something similar, so its better to collaborate and distribute task accordingly.
let me know if you need help in any planning or collaborating. Happy to setup a call as well.

**Comment by deshraj** [comment]
Hey @amjadraza, lets split the work in a way that we are not stepping on each other's toes here. 

Can you please update your PR to have the following changes only (I will take care of the rest in my PR):

- Issue template
- CI/CD configuration
- PR template
- Pre-commit hook

And then I will take care of:
- Adding black
- Adding ruff


We can work on adding poetry in a follow up PR.

**Comment by deshraj** [comment]
Hey @amjadraza, can you please update us if you are going to work on this feature? If you don't have bandwidth, thats totally fine. We will pick changes from your PR and incorporate. In any case, please let us know. Thanks!

**Comment by amjadraza** [comment]
@deshraj thanks, sorry was busy in family stuff. 

Your plan looks alright. Let us go step by step. 

Thanks

**Comment by deshraj** [comment]
Closing this PR since I believe we have added all the things from this PR from smaller follow up PRs.

Thanks a lot @amjadraza for taking initiative on this.

**Pull request closed without merging**
