### PR TITLE
feat: Add support for chat endpoint

### PR DESCRIPTION
**Pull request by taranjeet**
This commit introduces a new endpoint called chat. It maintains the context of the last 5 user messages and continues to do a semantic search to find the context.
Addresses https://github.com/embedchain/embedchain/issues/102

### CODE REVIEW

**Comment by taranjeet** [comment]
- need to update readme.

**Comment by cachho** [comment]
Nice to see that lang chain has a memory buffer. Here are my thoughts:

We should consider this as part of the configuration effort. You're adding another argument.

My main concern: Is this able to handle sessions in a client server model? How will it know what user said what and not mix up the history with simultaneous use? 

With that being said, I see how it would appeal to solo users that use this package for private purposes. It's definitely an improvement. For "pros" we should add a configuration option for history so they can do session management through the frontend. #113 I talk about this in this issue as well.

**Comment by taranjeet** [comment]
I see what you are saying. Chat history should be user specific and should be persisted to a db as well.

Opened two issues
- https://github.com/embedchain/embedchain/issues/153
- https://github.com/embedchain/embedchain/issues/154

**Comment by cachho** [comment]
> I see what you are saying. Chat history should be user specific and should be persisted to a db as well.
> 
> Opened two issues
> 
> * [Make chat history user specific #153](https://github.com/embedchain/embedchain/issues/153)
> * [Persist chat history #154](https://github.com/embedchain/embedchain/issues/154)

Good that you agree. Database is good, in the meantime, passing a list of strings as history will be possible from the state of the frontend, without a database. I will work on an implementation once we have agreed on a configuration.

**Pull request merged**
