### PR TITLE
Update chromadb dependency

### PR DESCRIPTION
**Pull request by mmurraysans**
## Description

This updates the ChromaDb dependency to allow newer version of ChromaDb.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Ran the included unit tests and lint checks to ensure everything still passed after dependency resolution.

Please delete options that are not relevant.

- [x] Unit Test

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

## Maintainer Checklist

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] Made sure Checks passed

### CODE REVIEW

**Comment by Dev-Khant** [comment]
@mmurraysans Thanks for making this change but unfortunately we can't directly update the Chromadb version for embedchain as other frameworks(like CrewAI) use our package and it causes dependency conflicts.

So please free to update chromadb locally,

**Comment by mmurraysans** [comment]
> @mmurraysans Thanks for making this change but unfortunately we can't directly update the Chromadb version for embedchain as other frameworks(like CrewAI) use our package and it causes dependency conflicts.
> 
> So please free to update chromadb locally,

sounds good and thanks for letting me know! would allowing a broader version range work maybe? that way other frameworks would still be able to pull the older version if needed?

**Comment by Dev-Khant** [comment]
Sure we can plan to include that. As a PR #1391 is already open for dependency issues, I would suggest you should close this PR and we can include all the changes there.

**Comment by mmurraysans** [comment]
sounds good. thanks!

**Pull request closed without merging**
