### PR TITLE
Add Ollama as a supported embedding provider

### LINKED ISSUE #1220: Ollama integration not working
### 🐛 Describe the bug

tried using the ollama example and i get openai.AuthenticationError: Error code: 401

here is the code.
import os
from embedchain import App

# load llm configuration from config.yaml file
app = App.from_config(config_path="config.yaml")
app.query("What is the capital of France?")

### PR DESCRIPTION
**Pull request by Echo3ToEcho7**
## Description

Add support for Ollama as an embedding provider

Fixes #1220

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation update

## How Has This Been Tested?

Updated configs/ollama.yaml and validated embedding test are passing. I also tested with local Ollama instance.

Please delete options that are not relevant.

- [x] Unit Test
- [ ] Test Script (please provide)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

## Maintainer Checklist

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] Made sure Checks passed

### CODE REVIEW

**Comment by Shubhamsaboo** [comment]
Any updates on this?

**Comment by theCyberTech** [comment]
Would love to get this implemented

**Comment by wilofice** [comment]
Would love to have this feature. Game changer

**Comment by jongirard** [comment]
Also need this feature before I can proceed

**Review by deshraj — APPROVED** [review]
Thanks for adding support for this feature.

**Comment by deshraj** [comment]
Will release this feature in the new version later tonight. :)

**Comment by flokoenig** [comment]
I was just trying to use this new feature and found that the OllamaEmbedderConfig does not accept the "vector_dimension" and other arguments, only model and base_url. Since ollama allows us to load several models, each with its own vector dimension (afaik, but then I'm completely new to this), shouldn't we also pass the other arguments?

With this hack, simply passing the rest of the config as kwargs, it seems to work:
```
@register_deserializable
class OllamaEmbedderConfig(BaseEmbedderConfig):
    def __init__(
        self,
        model: Optional[str] = None,
        base_url: Optional[str] = None,
        **kwargs
    ):
        super().__init__(model, **kwargs)
        self.base_url = base_url or "http://127.0.0.1:11434"
```

**Comment by Echo3ToEcho7** [comment]
When researching, it looked like Ollama didn't have a way to configure the vector size, so i didn't include it intentionally. Happy to add additional kwargs if that is the right way to go.

For reference: https://github.com/ollama/ollama/issues/651

**Comment by flokoenig** [comment]
Even if it is not configurable in ollama, different embedders produce vectors of different dimensions. E.g. I was trying to use avr/sfr-embedding-mistral which produces vectors of 4096, while milkey/gte produces 1024 dimensions. I assumed, that the embedding would then be cut down. 
However, I just saw that the chromadb holds embeddings of dim 4096 (for avr/sfr-embedding-mistral) even if the vector_dimension is not set. So obviously, I'm out of my depth here.
In any case it was kinda confusing, that vector_dimension was not recognized as an argument.

**Pull request merged**
