### PR TITLE
Option to select and use gpt-4

### PR DESCRIPTION
**Pull request by josebenitezg**
Add set_model to the App Class in order to add gpt-4 for better response.

### CODE REVIEW

**Comment by gasolin** [comment]
feel it will goes complex this way when user also want to config the embeddings etc, 
maybe pass through a config object when initiate the app? ex:

```
from embedchain import App

config = {
  model: 'gpt-4',
}
naval_chat_bot = App(config)
```

**Comment by harlev** [comment]
➕ 1

**Comment by josebenitezg** [comment]
solve conflicts, make some modifications and follow design patterns

**Comment by taranjeet** [comment]
hey @josebenitezg , this is a nice contribution.
I have introduced a new app type called `OpenSourceApp`, so it makes a lot of sense to keep `set_model` in `App` instead of the base class `Embedchain`.

One more feedback, thinking to call `set_model` as `set_llm_model`.
in future we can have a different variant of embedding model, so we can set it as `set_embedding_model`

Also, I am still thinking about config vs set_model approach. @harlev @gasolin @cachho would love your thoughts on this.

**Comment by cachho** [comment]
I think a default is missing.

**Comment by cachho** [comment]
> I have introduced a new app type called OpenSourceApp, so it makes a lot of sense to keep set_model in App instead of the base class Embedchain.

Why not on the `query` level? I think we should have a config on the query level.

We need to talk about this, I think set_* will be hard to maintain with a growing package, compared to a config dict or a configuration class.

**Comment by gasolin** [comment]
on the query level make more sense, but a default_model also a preferred way for most of the usage

here's my attempt (use config object) to solve the same issue https://github.com/embedchain/embedchain/pull/140

**Comment by cachho** [comment]
Please update this now that we have decided for a config model. thanks.

**Comment by taranjeet** [comment]
@cachho : i think this should be doable using config now. just that we need to update documentation where we can mention "gpt-4" as the model.

**Comment by cachho** [comment]
> @cachho : i think this should be doable using config now. just that we need to update documentation where we can mention "gpt-4" as the model.

agree. closing this.

**Pull request closed without merging**
