### PR TITLE
Add folder and branch to GitHub

### LINKED ISSUE #1243: [GitHub Loader] Add support for loading specific folder and branch of a github repository
### 🚀 The feature

Users want to load a specific folder from a github repository. Moreover, they want to load the data from a specific branch and not the default branch.

Screenshot 2024-02-06 at 11 17 27 AM

### Motivation, pitch

Requested by a user on discord community: https://discord.com/channels/1121119078191480945/1125758905310519327/1204150824868126790

### PR DESCRIPTION
**Pull request by Dev-Khant**
## Description

Add support for extraction of data from specific Branch or File.

Fixes #1243

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (does not change functionality, e.g. code style improvements, linting)
- [ ] Documentation update

## How Has This Been Tested?

Yes

Please delete options that are not relevant.

- [x] Unit Test
- [ ] Test Script (please provide)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

## Maintainer Checklist

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] Made sure Checks passed

### CODE REVIEW

**Comment by Dev-Khant** [comment]
Error not generated from my changes. Let me know how can I fix it.

**Review by deshraj — APPROVED** [review]
This is great. Thanks for adding support for this.

**Comment by deshraj** [comment]
Can you please check why the tests are failing?

**Comment by Dev-Khant** [comment]
@deshraj Error is caused because of `tests/evaluation/test_context_relevancy_metric.py`. Locall all the tests are passing.

Screenshot 2024-03-10 at 3 20 19 PM
Screenshot 2024-03-10 at 3 19 30 PM

**Comment by deshraj** [comment]
Oh interesting. Will merge this PR and debug it separately on my end. Thanks for this PR!

**Pull request merged**
