### PR TITLE
Added documentation

### PR DESCRIPTION
**Pull request by gen-ai-experts**

### CODE REVIEW

**Review by taranjeet — COMMENTED** [review]
Hi @balanagireddym thank you for your PR. Its a nice initiative to add doc strings so that code readability increases.
There is one minor comment. Please address that and let me know. Will merge the PR.

**Comment by taranjeet** [comment]
Hi @balam125 let me know if you have done the changes.

cc @cachho maybe you can chip in and review this PR.

**Comment by taranjeet** [comment]
Hey @cachho / @sahilyadav902 : lets wait for 2 days here for @balam125 to get back. If not then one of you can take this PR up, address the commits and resolve merge conflict. We can then proceed to merging it.

**Comment by taranjeet** [comment]
@deshraj / @aaishikdutta : do you want to take this up?

**Review by cachho — CHANGES_REQUESTED** [review]
Requires wording changes as pointed out by @taranjeet

**Comment by aaishikdutta** [comment]
@cachho this was closed with wording changes in a separate PR as there was no activity on this. I think we can close this PR

**Comment by cachho** [comment]
> @cachho this was closed with wording changes in a separate PR #219 as there was no activity on this. I think we can close this PR

You're probably right. It does fix a spelling error in `readme.md` though.

**Pull request closed without merging**
