### PR TITLE
Add metadata support to added data sources

### PR DESCRIPTION
**Pull request by Rayhanpatel**
Changes Made:
- Added optional `metadata` parameter to the `add` and `add_local` methods in the `EmbedChain` class.
- Modified the `load_and_embed` method to include the `metadata` parameter when adding documents.
- Updated the `_format_result` method to include metadata in the formatted results.

- If there are any mistakes, please correct this is my first commitment to opensource contribution

### CODE REVIEW

**Comment by deshraj** [comment]
Fixes #252

**Review by deshraj — APPROVED** [review]
Nice, thanks for adding this. ❤️

**Comment by Rayhanpatel** [comment]
Let me know if I can collaborate more thanks

**Comment by deshraj** [comment]
> Let me know if I can collaborate more thanks

For sure. Please feel free to glance through the issues and pick the unassigned ones if you are interested in contributing.

**Comment by cachho** [comment]
@Rayhanpatel What type are we expecting here? Do you have an example? Can we add this to readme? @taranjeet

**Comment by Rayhanpatel** [comment]
@cachho, should I add this? Let me know thanks
- The `metadata` parameter in the `add` method expects a dictionary object.
- The keys in the dictionary represent metadata attributes, while the values represent corresponding metadata values.
- Here's an example that demonstrates how to use the `metadata` parameter:

```python
# Example usage of the 'add' method with metadata
data_type = 'example'
url = 'https://example.com/example_data'
metadata = {
    'author': 'John Doe',
    'category': 'Sample Data',
    'date': '2023-07-15',
    'source': 'Data Repository',
    'description': 'This is an example dataset for testing purposes.'
}
app.add(data_type, url, metadata=metadata)
```

- In the example above, we provided metadata attributes such as author, category, date, source, and description.
- You can customize the metadata attributes based on your specific use case.

**Comment by Rayhanpatel** [comment]
#279
@cachho 
I made a change in the readme.md file. If you need any further changes, please let me know.

**Pull request merged**
