### PR TITLE
Update youtube_video.py

### PR DESCRIPTION
**Pull request by missioncfwf**
error if "No data found"

wrap error in try function and print "Error loading data from YouTube video", then empty list returned if error (for the video and not the playlist)

### CODE REVIEW

**Comment by cachho** [comment]
thanks for the PR. Blindly catching all exceptions is never advised, and I'm of the opinion that we shouldn't just ignore all exceptions and keep the code running.

If you want to do that, it takes 3 extra lines.
```python
try:
    app.add(...)
except Exception:
    pass
```

But maybe some users (like me) want to see errors and handle them in a unique way. That's not possible if no error is returned. I know you could handle an empty list as an error.

With that being said, I'm not against abstracting errors on the embedchain level, it just shouldn't turn into a script that just runs through no matter what.

**Comment by taranjeet** [comment]
@cachho @deshraj : what do you think about this?

**Comment by cachho** [comment]
I'm very much against it if I'm being blunt. We should add embedchain level exception handling at some point, but just escaping an exception is not the way to do it. The user should handle this. Maybe people want to, idk, keep a list with videos that have been deleted or something. If you escape the error and act like nothing happened you can't do that.

Please close. Don't take it personal.

**Comment by taranjeet** [comment]
@deshraj : what do you think about this?

**Comment by deshraj** [comment]
Agree with @cachho on this one. Handling data loading errors should be done by the user. Catching this exception in the python package could cause some silent regressions which is not good.

**Comment by deshraj** [comment]
@missioncfwf sorry but we would have to close this PR. Appreciate your contribution. 🙇

**Pull request closed without merging**
