### PR TITLE
[Feature] Google Drive Folder support as a data source

### LINKED ISSUE #525: Feature request: Google drive folder/instance as a data source
### 🚀 The feature

Rather than adding one document at a time, enable the bot to ingest an entire google folder or directory structure

### Motivation, pitch

often times, the knowledge on which you want to train the bot is already curated, Pointing it to that repository rather than having to manually enter the URL of each and every file will save a lot of setup time and as well as make supporting more dynamic knowledge bases easier - you don't have to have a preconceived notion of how the knowledge is divided and across which files.

### PR DESCRIPTION
**Pull request by JoeSL**
## Description

This change allows embedchain users to use a google drive folder as a data source. This is done by building a wrapper around Langchain's GoogleDriveLoader.

Fixes #525 

## Type of change

Please delete options that are not relevant.
- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
This feature was tested by creating the appropriate unit tests and testing the feature through documentation client code by setting the  data_type as "google_drive_folder"
It is important to correctly setup the google API credentials in order for this feature to work.

Please delete options that are not relevant.
- Unit Test

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

## Maintainer Checklist

- [x] closes #525  (Replace xxxx with the GitHub issue number)
- [x] Made sure Checks passed

### CODE REVIEW

**Comment by deshraj** [comment]
Thanks @JoeSL for the PR. This is going to be really useful for the community. 

Can you please do the following before we can review the PR:
- Resolve conflicts
- Rename the files, classes and other things from `Google Drive Folder` to `Google Drive`? We want to keep the effort low for the users when adding data sources. So, `google_drive_folder` will become `google_drive`, `GoogleDriveFolderChunker` will become `GoogleDriveChunker` and so on.

Thanks again for this PR.

**Comment by JoeSL** [comment]
Hello @deshraj, Kindly find the PR again with the requested changes.

**Review by deshraj — APPROVED** [review]
Looks good. Thanks for adding this feature.

**Comment by JoeSL** [comment]
> Looks good. Thanks for adding this feature.
The pleasure is mine. Embedchain is a great framework! Please let me know if you have any other issues I can help with.

**Pull request merged**
