### PR TITLE
Upgrade the chromadb version to 0.4.8 and open its settings configuration.

### LINKED ISSUE #516: Upgrade the chromadb version to 0.4.8 and open its settings configuration.
### 🚀 The feature

Currently, the Setting of chromadb is not open to users. Users cannot make any configurations, such as performing security authentication. We need to open up the settings of chromadb.

Please look this docs:  https://docs.trychroma.com/usage-guide#basic-authentication

```python
settings = Settings(chroma_client_auth_provider="chromadb.auth.basic.BasicAuthClientProvider",
                chroma_client_auth_credentials="admin:admin"))
```

I will submit a pr for this, thanks!

### Motivation, pitch

We need to enhance the functionality of chromadb.

### LocalTest

```python
DB_SETTINGS = {
        "chroma_client_auth_provider": "chromadb.auth.basic.BasicAuthClientProvider",
        "chroma_client_auth_credentials": "admin:admin"
    }

config = CustomAppConfig(log_level='INFO',
                             host="localhost",
                             port="8000",
                             collection_name="chromadb",
                             provider=Providers.OPENAI,
                             embedding_fn=EmbeddingFunctions.OPENAI,
                             chroma_settings=DB_SETTINGS
)

my_bot = App(config)
```

### PR DESCRIPTION
**Pull request by mggger**
## Description
1.  update the chromadb version to 0.4.8
2. allow user can set chromadb settings

Fixes #516 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

Please delete options that are not relevant.

- [x] Unit Test
- [ ] Test Script (please provide)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

## Maintainer Checklist

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] Made sure Checks passed

### CODE REVIEW

**Comment by mggger** [comment]
@candidosales  @gasolin  please help to review 😊

**Comment by cachho** [comment]
Hey, I'm working on a refactor for the whole database and how it's configured. So I think we're going to have to work on some merge conflicts.

**Comment by mggger** [comment]
@cachho 

Okay, if possible in the future, please provide a separate branch for refactoring. I can submit the relevant code on that branch.

**Review by taranjeet — APPROVED** [review]

**Comment by taranjeet** [comment]
@mggger : thanks for your contribution. Looks good to me.

Can you please resolve the merge conflict?

**Comment by taranjeet** [comment]
Hi @mggger , can you check why the tests are failing?

**Comment by mggger** [comment]
@taranjeet  Got it, due to the removal of the "allow_reset" configuration option, the unit test did not pass. It has been fixed.

**Comment by taranjeet** [comment]
@mggger : the test are still failing. Can you please check?

**Comment by mggger** [comment]
@taranjeet  I'm sorry, previously I only ran `test_chroma_db.py`, but this time I ran all the unit tests.

**Comment by taranjeet** [comment]
No worries.
thanks for your PR @mggger 
Merged it

**Comment by cachho** [comment]
I noticed that you disabled allow_reset=True @mggger

**Comment by mggger** [comment]
@cachho  Please check the review message above. I left a comment in the review, but it doesn't seem to have been followed up on.

**Comment by cachho** [comment]
> @taranjeet Got it, due to the removal of the "allow_reset" configuration option, the unit test did not pass. It has been fixed.

but how has it been fixed?

**Comment by mggger** [comment]
@cachho  Create app with `allow_reset` 

```
 app = App(
            CustomAppConfig(
                provider=Providers.OPENAI, embedding_fn=EmbeddingFunctions.OPENAI, chroma_settings={"allow_reset": True}
            )
        )
```

**Pull request merged**
