### PR TITLE
Rename 'vectordb' folder to 'vector_db'

### LINKED ISSUE #734: Follow snake case convention in folder vectordb
### 🐛 Describe the bug

Located at  embedchain/config/vectordb

It should be vector_db.

This task will involve changing the relevant imports everywhere and making sure that tests pass and nothing breaks.

### PR DESCRIPTION
**Pull request by Prikshit7766**
## Description

This pull request renames the 'vectordb' folder to 'vector_db' to follow snake_case convention.

Fixes #734

## Type of change

Please delete options that are not relevant.

- [ ] Refactor (does not change functionality, e.g. code style improvements, linting)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

## Maintainer Checklist

- [ ] closes #734
- [ ] Made sure Checks passed

### CODE REVIEW

**Comment by taranjeet** [comment]
Hey @Prikshit7766 , thanks for your contribution.
You will also have to all the imports and related code in the docs folder.

**Comment by Prikshit7766** [comment]
> You will also have to all the imports and related code in the docs folder.

Thank you for your feedback. Upon reviewing the code, it appears that the imports in the documentation (docs) folder should not require any changes. The imports for `OpenSearchDBConfig`, `ElasticsearchDBConfig`, and `ChromaDbConfig` from the `vector_db` module in the `config` package should still be valid.

In the documentation, we have imports like:
```python
from embedchain.config import CustomAppConfig, ElasticsearchDBConfig

**Comment by taranjeet** [comment]
Example
```
docs/advanced/app_types.mdx:You can choose one by importing it from `embedchain.vectordb`. E.g.:
docs/advanced/app_types.mdx:from embedchain.vectordb.elasticsearch import ElasticsearchDB
docs/advanced/app_types.mdx:from embedchain.vectordb.elasticsearch import ElasticsearchDB
docs/advanced/app_types.mdx:from embedchain.vectordb.chroma import ChromaDB
docs/advanced/app_types.mdx:from embedchain.vectordb.elasticsearch import ElasticsearchDB
docs/advanced/vector_database.mdx:from embedchain.vectordb.elasticsearch import ElasticsearchDB
docs/advanced/vector_database.mdx:from embedchain.vectordb.elasticsearch import ElasticsearchDB
docs/advanced/vector_database.mdx:from embedchain.vectordb.opensearch import OpenSearchDB
```

You can try running `git grep vectordb` to see all the places.

Let me know if any doubts.

**Comment by Prikshit7766** [comment]
> embedchain.vectordb.opensearc

I think then we also need to change 'embedchain/vectordb' to 'embedchain/vector_db'

**Pull request closed without merging**
