### PR TITLE
Add support for Azure, OpenAI, Palm, Anthropic, Cohere, Replicate Models - using litellm

### PR DESCRIPTION
**Pull request by ishaan-jaff**
## Description
This PR adds support for models from all the above mentioned providers using https://github.com/BerriAI/litellm
addresses: https://github.com/embedchain/embedchain/issues/346
TLDR: Embedchain gets:
- more models out of the box
- instant integration of models by modifying the `model` param (Easy to add models in the future)
- log I/O to Posthog, Sentry, Helicone, Supabase without making any code changes & get API Key management 

- instead of maintaining multiple functions for each provider `_get_vertex_answer`, `_get_athrophic_answer` embedchain can use one function `_get_openai_answer` to call all models

Here's a sample of how litellm completion is used:

```python
from litellm import completion

## set ENV variables
# ENV variables can be set in .env file, too. Example in .env.example
os.environ["OPENAI_API_KEY"] = "openai key"
os.environ["COHERE_API_KEY"] = "cohere key"

messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion(model="gpt-3.5-turbo", messages=messages)

# cohere call
response = completion("command-nightly", messages)

# anthropic call
response = completion(model="claude-instant-1", messages=messages)
```
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (does not change functionality, e.g. code style improvements, linting)
- [ ] Documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

Please delete options that are not relevant.

- [ ] Unit Test
- [ ] Test Script (please provide)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

## Maintainer Checklist

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] Made sure Checks passed

### CODE REVIEW

**Comment by cachho** [comment]
Thanks for your PR.

If we go this route, all providers we want to add in the future need to be supported by your package. Why would we rely this heavily on your package? I'm sorry to say it, but I don't see the "secret sauce". You also just call the provider's function, we can do that inside embedchain without relying on external dependencies.

We aren't that desperate to add new models, it's not that it's too hard, we just didn't see a user demand for more niche models.

The only thing that intrigues me personally are the logging callback functions your package includes. But I guess we couldn't use them with this PR alone?

Please let me know if I got anything wrong.

**Comment by krrishdholakia** [comment]
Hi @taranjeet, 

Seems like 
https://github.com/embedchain/embedchain/issues/687
https://github.com/embedchain/embedchain/issues/684
https://github.com/embedchain/embedchain/issues/686

would be resolved by integrating ChatLiteLLM - https://python.langchain.com/docs/integrations/chat/litellm

I'd love to understand what LiteLLM missing to be helpful here @taranjeet

**Comment by deshraj** [comment]
Hi @krrishdholakia, thanks for your help in this issue. It looks like @sidmohanty11 has already been working on these issues and already have a pull request up for the same.

**Comment by krrishdholakia** [comment]
cc: @sidmohanty11 happy to collaborate on this if that's helpful

**Pull request closed without merging**
