### PR TITLE
Fix OpenAI Assistant

### LINKED ISSUE #1369: ImportError: cannot import name 'MessageContentText' from 'openai.types.beta.threads'
#### Description:
When using OpenAI version > 1.13.4 in pip dependencies, the following error occurs:

```
ImportError: cannot import name 'MessageContentText' from 'openai.types.beta.threads'
```

This error arises because `MessageContentText` is not present in `openai.types.beta.threads`.

#### Steps to Reproduce:
1. Use OpenAI assistants.
2. Import `OpenAIAssistant` using:
   ```python
   from embedchain.store.assistants import OpenAIAssistant
   ```
3. The error mentioned above will be triggered.

Please ensure the OpenAI version in your dependencies is <= 1.13.4 to avoid this issue.

### PR DESCRIPTION
**Pull request by Dev-Khant**
## Description

Fixes openai assistant. PLEASE USE OPENAI==1.20.0 (https://github.com/openai/openai-python/issues/1416)

Fixes #1369

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- [x] Unit Test
- [ ] Test Script (please provide)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

## Maintainer Checklist

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] Made sure Checks passed

### CODE REVIEW

**Comment by Dev-Khant** [comment]
It's working now locally with `openai==1.20.0`
Screenshot 2024-06-08 at 6 28 43 PM

**Comment by denaha** [comment]
the langchain module expects a higher version
`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.`
`langchain-openai 0.1.7 requires openai<2.0.0,>=1.24.0, but you have openai 1.20.0 which is incompatible.`

**Comment by denaha** [comment]
Still gives the same error 
```
Name: openai
Version: 1.20.0
Summary: The official Python library for the openai API
```
```
from openai.types.beta.threads import MessageContentText, ThreadMessage
ImportError: cannot import name 'MessageContentText' from 'openai.types.beta.threads' (/site-packages/openai/types/beta/threads/__init__.py)
```

**Comment by Dev-Khant** [comment]
> Still gives the same error
> 
> ```
> Name: openai
> Version: 1.20.0
> Summary: The official Python library for the openai API
> ```
> 
> ```
> from openai.types.beta.threads import MessageContentText, ThreadMessage
> ImportError: cannot import name 'MessageContentText' from 'openai.types.beta.threads' (/site-packages/openai/types/beta/threads/__init__.py)
> ```

@denaha Please can you check the imports I have changed in this PR. It will fix the issue(attached screenshot)

**Comment by Dev-Khant** [comment]
> the langchain module expects a higher version `ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.` `langchain-openai 0.1.7 requires openai<2.0.0,>=1.24.0, but you have openai 1.20.0 which is incompatible.`

Please for now you can have this version locally, I'll change the version of langchain_openai in this PR https://github.com/embedchain/embedchain/pull/1391

**Comment by denaha** [comment]
I changed the import from AIAssistant to OpenAIAssistant and still get the same error.
```
from embedchain.store.assistants import OpenAIAssistant
  File "/site-packages/embedchain/store/assistants.py", line 11, in <module>
    from openai.types.beta.threads import MessageContentText, ThreadMessage
ImportError: cannot import name 'MessageContentText' from 'openai.types.beta.threads' (/site-packages/openai/types/beta/threads/__init__.py)
```

**Review by deshraj — APPROVED** [review]
Thanks for fixing this.

**Comment by denaha** [comment]
Thanks for quickly fixing this. Works now with the latest version of embedchain

**Pull request merged**
