### PR TITLE
add workflow diagram outlining the process of embedchain

### PR DESCRIPTION
**Pull request by CreativeSelf0**
## Description

Add a visual workflow image that represents the workflow behind embedchain. It will allow people to understand the process more easily.

## Type of change

1. Add a workflow image to the documentation.
2. Used the same process of adding an image to the docs
3. Add an image to `docs/images` and reference it using the frame.

- [x] Documentation update

## How Has This Been Tested?

ran the `minitlify dev` to see if changes have been reflected.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by CreativeSelf0** [comment]
@deshraj here's the upate.

**Comment by deshraj** [comment]
@CreativeSelf0 thanks. Can you please let me know how did you create this chart? I would like to do some changes in there before we merge it to the docs?

**Comment by CreativeSelf0** [comment]
@deshraj I mostly use [excalidarw](https://excalidraw.com/), it's pretty decent tool. I love it.

**Comment by taranjeet** [comment]
thanks for your contribution @CreativeSelf0 . This is a great one.
But we will have to close this one, as the architecture has changed a lot.
We plan to publish a new one in the future.

**Pull request closed without merging**
