### PR TITLE
#1128 | Remove deprecated type hints from typing module

### LINKED ISSUE #1128: Replace deprecated type aliases from typing module
As detailed in [PEP 585](https://peps.python.org/pep-0585/#implementation), some type aliases are to be deprecated as of Python 3.9, so they should be replaced by the ones indicated in the previous link.

I'm happy to do it myself, if admins could please assign, thanks!

### PR DESCRIPTION
**Pull request by sandrasgg**
## Description

Remove [deprecated](https://peps.python.org/pep-0585/#implementation) type hints from typing module

Fixes #1128 

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- [X] Unit Test

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [X] I have checked my code and corrected any misspellings

## Maintainer Checklist

- [ ] closes #1128
- [ ] Made sure Checks passed

### CODE REVIEW

**Comment by deshraj** [comment]
@sandrasgg looks like these conflicts are ther after I merged your previous PR. Can you please resolve these so that we can review the code? Thanks!

**Comment by sandrasgg** [comment]
@deshraj I've rebased with main and resolved the conflicts, it's ready to review 👌🏼

**Comment by sandrasgg** [comment]
@deshraj I see there's a conflict again, I'll resolve it soon and let you know

**Review by deshraj — APPROVED** [review]
This is great. Thanks for fixing it.

**Pull request merged**
