### PR TITLE
fix: chroma pysqlite version

### PR DESCRIPTION
**Pull request by cachho**
## Description

When running the new embedchain upgrade with `Chroma 0.4.2`, I get the following error.

`ERROR tests/chunkers/test_text.py - RuntimeError: Your system has an unsupported version of sqlite3. Chroma requires sqlite3 >= 3.35.0.Please visit https://docs.trychroma.com/troubleshooting#sqlite to learn how to upgrade.`

This PR implements the proposed fix from the troubleshooting guide, by replacing sqlite3 with pysqlite3.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

Please delete options that are not relevant.

- [ ] Unit Test *tests currently fail*
- [X] Test Script (please provide)

```
from embedchain import App
from embedchain.config import AppConfig

app = App(config=AppConfig(log_level="DEBUG"))
app.add("text", "lorem ipsum")
```

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules
- [X] I have checked my code and corrected any misspellings

## Maintainer Checklist

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] Made sure Checks passed

### CODE REVIEW

**Comment by cachho** [comment]
Python 3.11.4 shipped with sqlite 3.31 - ChromaDB requires 3.35. So simply bumping the required python version won't do it.

**Comment by taranjeet** [comment]
thanks @cachho for this catch. @deshraj : would love your review as well.

**Comment by cachho** [comment]
> thanks @cachho for this catch. @deshraj : would love your review as well.

I'm wondering how everyone else does it? How did you get the right version?

**Comment by cachho** [comment]
The official chroma distribution is using this same workaround approach for google collab. Only that they install it on the spot when needed, I will change my code to do the same.

https://github.com/chroma-core/chroma/pull/851/files

**Comment by cachho** [comment]
I had further discussions about this with the Chroma team. They said that this only works on linux, so I added a check for the OS. https://github.com/chroma-core/chroma/issues/874

**Review by taranjeet — APPROVED** [review]

**Comment by deshraj** [comment]
Thanks for looking into this @cachho.

**Pull request merged**
