### PR TITLE
[refactor] syntax cleanup

### PR DESCRIPTION
**Pull request by gasolin**
- remove redundant tab/space
- ~~reuse ef declaration~~

### CODE REVIEW

**Comment by cachho** [comment]
You made me rethink the whole part, but it has a logical error, the declaration is not the problem. this is fixed in #175. The double declaration is purposely because otherwise it would instantiate the open source embedding, even if you provide your own, which is inefficient.

I will get #175 merged, please remove that part from your code. Thanks.

**Comment by gasolin** [comment]
removed ef related patch

**Comment by cachho** [comment]
waiting for merge of #175 then

**Comment by taranjeet** [comment]
thanks @gasolin for this. We need to setup a proper linting guideline as well.

**Review by taranjeet — APPROVED** [review]

**Pull request merged**
